apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-stag
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:lucaspwk/gitops-k8s-demo.git
    targetRevision: HEAD
    path: envs/stag
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
